version: '2'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - "./web/src:/app/src"

    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user1:123456@database/db
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 123456
